Control Registry
CommandrMoose/TardisRefined pull request #217
Opened 2024-04-02 22:17 UTC by Duzos

Converts the `ConsoleControl` enum into a Registry for `Control`s
Allows for other mods to add their own controls.

2024-04-02 22:48 UTC, Jeryn99 reviewed
I am leaving @50ap5ud5 to review this as it is registry related but I am not a fan of abusing the super like this ``super(new ResourceLocation(TardisRefined.MODID, "door_toggle"));``

If a mod wanted to extend one of the existing controls, this would complicate things

2024-04-02 22:49 UTC, Duzos commented
i love abusing super :(
i will change so theres multiple constructors or smth if wanted then

2024-04-02 22:50 UTC, Jeryn99 commented
> i love abusing super :( i will change so theres multiple constructors or smth if wanted then

Yea sounds good

2024-04-06 00:47 UTC, 50ap5ud5 requested changes
Looks great, some minor cleanup and this will be good to go.

2024-04-06 00:47 UTC, 50ap5ud5 commented on common/src/main/java/whocraft/tardis_refined/common/tardis/control/Control.java
> +    }
getSerialializedName looks to be a holdover from when the Control was an Enum, if this is not being used we don't need this.

2024-04-11 11:27 UTC, 50ap5ud5 approved these changes
LGTM

2024-04-11 11:28 UTC, merged