Immersive Portals!
CommandrMoose/TardisRefined pull request #84
Opened 2023-02-01 19:26 UTC by Suff99

This pull request was worked on by myself and @thejudge156 

It supplies Immersive Portals support for the mod for both the shell and the interior.
Shells that do not have any portal information given, will operate without portals like the mods default behaviour.

Fabric users simply need to install any version of Immersive Portals and Fabric API, but Forge users will need to use Immersive Portals 2.3.2 and onwards; using earlier versions will cause the game to close to avoid users pointing out a crash where adding a dimension via code would crash the game with a crash report.

The compatibility will be optional via the implemented config file (the only exception being on Fabric, where dimensions NEED to be handled via Immersive Portals) 

![2023-02-01_19 25 03](https://user-images.githubusercontent.com/36424503/216142860-095ec004-8a26-49b8-b10e-05020d55fe2c.png)
![2023-02-01_19 25 16](https://user-images.githubusercontent.com/36424503/216142863-cc0a74cc-d7cd-463e-8061-2856663608bc.png)
![2023-02-01_19 24 15](https://user-images.githubusercontent.com/36424503/216142864-5d90cc3a-4e86-42d2-a1f1-1aac796af0ab.png)
![2023-01-07_19 43 39](https://user-images.githubusercontent.com/36424503/216142888-11ea6ab5-4998-4420-b469-a398c3745930.png)

2023-02-02 06:36 UTC, CommandrMoose reviewed
Feels way more solid than it has before. I have found a few bugs that are either in relation to or are more present when using this feature.

BUG: Leaving the game and rejoining whilst inside the cave makes the growth door no longer function.
BUG: Placing a door inside the root cave creates a portal for the growth shell
BUG: Default shell's portal is not aligned with the interior view - doors are distinctively lower inside when looking from the outside
BUG: You cannot view the external shell's model whilst inside - doors that open outwards are not visible.
BUG: Door sounds can be heard twice when the door is closed
BUG: Throwing items through the door will cause them to spaz out
BUG: Breaking the shell in creative causes the model to no longer render until the next interaction.

Before merging, please make sure that everything is operational and works as intended by building and using the TARDIS without immersive portals installed.

2023-02-02 10:45 UTC, Suff99 commented on common/src/main/java/whocraft/tardis_refined/compat/portals/ImmersivePortals.java
> +        themeToOffsetMap.put(ShellTheme.FACTORY, List.of(new Vec3(0.499, 0, 0),
Done

2023-02-02 10:46 UTC, Suff99 commented on common/src/main/java/whocraft/tardis_refined/compat/portals/TARDISPortalData.java
> +public interface TARDISPortalData {
Renamed

2023-02-02 10:47 UTC, Suff99 commented on forge/src/main/java/whocraft/tardis_refined/common/capability/forge/TardisLevelOperatorImpl.java
> +            System.out.println("what the fuck");
Removed

2023-02-02 10:50 UTC, Suff99 commented on common/src/main/java/whocraft/tardis_refined/client/model/blockentity/shell/ShellModelCollection.java
> +import whocraft.tardis_refined.client.model.blockentity.console.ConsoleModelCollection;
Removed

2023-02-02 10:52 UTC, Suff99 commented on common/src/main/java/whocraft/tardis_refined/common/blockentity/door/GlobalDoorBlockEntity.java
> +                if (!cap.getControlManager().isInFlight() && !door.locked() && serverLevel.dimensionTypeId().equals(DimensionTypes.TARDIS)) {
Removed

2023-02-02 10:55 UTC, Suff99 commented on common/src/main/java/whocraft/tardis_refined/client/model/blockentity/door/VendingMachineDoorModel.java
> +        this.door.xRot = (open) ? -1.6f : 0;
Fixed

2023-02-02 10:55 UTC, Suff99 commented on common/src/main/java/whocraft/tardis_refined/client/model/blockentity/door/PresentDoorModel.java
> +		this.door.xRot = (open) ? -1.5f:0;
Fixed

2023-02-02 10:57 UTC, Suff99 commented on common/src/main/java/whocraft/tardis_refined/client/model/blockentity/door/PhoneBoothDoorModel.java
> +		this.Door2.yRot = (open) ? 1.75f : 0;
Fixed

2023-02-02 10:59 UTC, Suff99 commented
- [ ] BUG: Leaving the game and rejoining whilst inside the cave makes the growth door no longer function.
- [ ] BUG: Placing a door inside the root cave creates a portal for the growth shell
- [ ] BUG: Default shell's portal is not aligned with the interior view - doors are distinctively lower inside when looking from the outside
- [ ] BUG: You cannot view the external shell's model whilst inside - doors that open outwards are not visible.
- [ ] BUG: Door sounds can be heard twice when the door is closed
- [ ] BUG: Throwing items through the door will cause them to spaz out
- [ ] BUG: Breaking the shell in creative causes the model to no longer render until the next interaction.

2023-02-11 23:44 UTC, 50ap5ud5 requested changes
Amazing work!

2023-02-11 23:44 UTC, 50ap5ud5 commented on common/build.gradle
> +
Would be good to set a gradle variable for the IP dependencies

2023-02-11 23:44 UTC, 50ap5ud5 commented on common/src/main/java/whocraft/tardis_refined/common/tardis/manager/TardisInteriorManager.java
> +        System.out.println(tag);
Remove prints

2023-02-11 23:44 UTC, 50ap5ud5 commented on fabric/src/main/java/whocraft/tardis_refined/fabric/events/ModEvents.java
> +    public static JsonElement getResponse(URL url) throws IOException {
What is this used for? Seems to not be called anywhere.

2023-02-11 23:51 UTC, 50ap5ud5 approved these changes

2023-02-12 00:42 UTC, CommandrMoose approved these changes

2023-02-12 00:44 UTC, merged

2023-12-22 22:17 UTC, Noklle commented
Looks stunning, but I came across a weird issue

BUG: The collision of the door block prevents entry and exit. This can be circumvented in the overworld by jumping on top of the block, upon which you fall into it and can walk into the TARDIS, but this doesn't work when trying to exit the TARDIS. Works fine in spectator mode, given the lack of collision.

2023-12-22 22:20 UTC, Suff99 commented
It's been fixed pending release